recipe_sha: ac315c56b5195494365d0b3d519a486b13414db0d8f69b993c9707f891766c12  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
      unlink_precs, link_precs = self.solve_for_diff(
    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 221, in solve_for_diff
      final_precs = self.solve_final_state(
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 223, in solve_final_state
      out_state = self._solving_loop(in_state, out_state, index)
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 303, in _solving_loop
      solved = self._solve_attempt(in_state, out_state, index, attempt=attempt)
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 414, in _solve_attempt
      new_conflicts = self._maybe_raise_for_problems(
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 712, in _maybe_raise_for_problems
      self._maybe_raise_for_conda_build(
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
      raise exc
  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("zlib=1.2"), MatchSpec("python==2.7.12=0")}
  Encountered problems while solving:
    - package python-2.7.12-0 requires zlib 1.2.*, but none of the providers can be installed

  Could not solve for environment specs
  The following packages are incompatible
   [32mlibzlib >=1.3.1,<2.0a0 [0m is installable with the potential options
     [32mlibzlib 1.3.1[0m would require
       [32mzlib 1.3.1 *_0[0m, which can be installed;
     [32mlibzlib 1.3.1[0m would require
       [32mzlib 1.3.1 *_1[0m, which can be installed;
     [32mlibzlib 1.3.1[0m would require
        [32mzlib 1.3.1 *_2[0m, which can be installed;
   [31mpython 2.7.* [0m is not installable because there are no viable options
      [31mpython [2.7.12|2.7.13][0m would require
        [31mzlib 1.2.* [0m, which conflicts with any installable versions previously reported;
      [31mpython 2.7.14[0m would require
        [31mzlib 1.2.8 [0m, which conflicts with any installable versions previously reported;
      [31mpython [2.7.14|2.7.15][0m would require
        [31mzlib [1.2.11 |1.2.11.* ][0m, which conflicts with any installable versions previously reported;
      [31mpython 2.7.15[0m would require
         [31mzlib >=1.2.11,<1.3.0a0 [0m, which conflicts with any installable versions previously reported.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2439, in build
      create_build_envs(top_level_pkg, notest)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2277, in create_build_envs
      raise e
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2250, in create_build_envs
      environ.get_package_records(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 938, in get_install_actions
      precs = get_package_records(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 938, in get_install_actions
      precs = get_package_records(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 938, in get_install_actions
      precs = get_package_records(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 891, in get_install_actions
      _actions = _install_actions(prefix, index, specs, subdir=subdir)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1307, in install_actions
      txn = solver.solve_for_transaction(prune=False, ignore_pinned=False)
    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
      unlink_precs, link_precs = self.solve_for_diff(
    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 221, in solve_for_diff
      final_precs = self.solve_final_state(
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 223, in solve_final_state
      out_state = self._solving_loop(in_state, out_state, index)
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 303, in _solving_loop
      solved = self._solve_attempt(in_state, out_state, index, attempt=attempt)
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 414, in _solve_attempt
      new_conflicts = self._maybe_raise_for_problems(
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 712, in _maybe_raise_for_problems
      self._maybe_raise_for_conda_build(
    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
      raise exc
  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("zlib=1.2"), MatchSpec("python==2.7.12=0")}
  Encountered problems while solving:
    - package python-2.7.12-0 requires zlib 1.2.*, but none of the providers can be installed

  Could not solve for environment specs
  The following packages are incompatible
   [32mlibzlib >=1.3.1,<2.0a0 [0m is installable with the potential options
     [32mlibzlib 1.3.1[0m would require
       [32mzlib 1.3.1 *_0[0m, which can be installed;
     [32mlibzlib 1.3.1[0m would require
       [32mzlib 1.3.1 *_1[0m, which can be installed;
     [32mlibzlib 1.3.1[0m would require
        [32mzlib 1.3.1 *_2[0m, which can be installed;
   [31mpython 2.7.* [0m is not installable because there are no viable options
      [31mpython [2.7.12|2.7.13][0m would require
        [31mzlib 1.2.* [0m, which conflicts with any installable versions previously reported;
      [31mpython 2.7.14[0m would require
        [31mzlib 1.2.8 [0m, which conflicts with any installable versions previously reported;
      [31mpython [2.7.14|2.7.15][0m would require
        [31mzlib [1.2.11 |1.2.11.* ][0m, which conflicts with any installable versions previously reported;
      [31mpython 2.7.15[0m would require
         [31mzlib >=1.2.11,<1.3.0a0 [0m, which conflicts with any installable versions previously reported.
# Last 100 lines of the build log.
