recipe_sha: f3f2c1bbefdf1e99911e0d1d4f403990baeeedf254257d438ed54d1d17df8c3c  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-

  Packaging flye
  Packaging flye-2.9.5-py312he0d4a5b_2






  WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
  compiling .pyc files...
  number of files: 104
     INFO: sysroot: '/System/Library/Frameworks/' files: '['vmnet.framework/Versions/Current', 'vmnet.framework/Versions/A/_CodeSignature/CodeResources', 'vmnet.framework/Versions/A/Resources/version.plist', 'vmnet.framework/Versions/A/Resources/InfoPlist.loctable']'
     INFO: sysroot: '/usr/lib/' files: '['zsh/5.9/zsh/zselect.so', 'zsh/5.9/zsh/zpty.so', 'zsh/5.9/zsh/zprof.so', 'zsh/5.9/zsh/zleparameter.so']'
     INFO: sysroot: '/opt/X11/' files: '[]'
     INFO (flye,bin/flye-minimap2): Needed DSO /System/Library/Frameworks/libSystem.B.dylib found in $SYSROOT
     INFO (flye,bin/flye-minimap2): Needed DSO lib/libz.1.dylib found in conda-forge/osx-64::libzlib==1.3.1=hd23fc13_2
     INFO (flye,bin/flye-samtools): Needed DSO lib/libz.1.dylib found in conda-forge/osx-64::libzlib==1.3.1=hd23fc13_2
     INFO (flye,bin/flye-samtools): Needed DSO /System/Library/Frameworks/libSystem.B.dylib found in $SYSROOT
     INFO (flye,bin/flye-modules): Needed DSO lib/libz.1.dylib found in conda-forge/osx-64::libzlib==1.3.1=hd23fc13_2
     INFO (flye,bin/flye-modules): Needed DSO lib/libc.1.dylib found in conda-forge/osx-64::libcxx==19.1.5=hf95d169_0
     INFO (flye,bin/flye-modules): Needed DSO /System/Library/Frameworks/libSystem.B.dylib found in $SYSROOT
     INFO (flye): Interpreted package 'flye' is interpreted by 'python'
  Fixing permissions
  Packaged license file/s.
  INFO :: Time taken to mark (prefix)
          0 replacements in 0 files was 0.08 seconds
  Files containing CONDA_PREFIX
  -----------------------------
  bin/flye (text): Patching
  TEST START: /opt/mambaforge/envs/bioconda/conda-bld/osx-64/flye-2.9.5-py312he0d4a5b_2.tar.bz2
  Renaming work directory '/opt/mambaforge/envs/bioconda/conda-bld/flye_1733981834095/work' to '/opt/mambaforge/envs/bioconda/conda-bld/flye_1733981834095/work_moved_flye-2.9.5-py312he0d4a5b_2_osx-64'
  shutil.move(work)=/opt/mambaforge/envs/bioconda/conda-bld/flye_1733981834095/work, dest=/opt/mambaforge/envs/bioconda/conda-bld/flye_1733981834095/work_moved_flye-2.9.5-py312he0d4a5b_2_osx-64)
  Reloading output folder (local): ...working... done
  Solving environment (_test_env): ...working... done

  ## Package Plan ##

    environment location: /opt/mambaforge/envs/bioconda/conda-bld/flye_1733981834095/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac


  The following NEW packages will be INSTALLED:

      bzip2:           1.0.8-hfdf4475_7          conda-forge
      ca-certificates: 2024.8.30-h8857fd0_0      conda-forge
      flye:            2.9.5-py312he0d4a5b_2     local
      libcxx:          19.1.5-hf95d169_0         conda-forge
      libexpat:        2.6.4-h240833e_0          conda-forge
      libffi:          3.4.2-h0d85af4_5          conda-forge
      liblzma:         5.6.3-hd471939_1          conda-forge
      libsqlite:       3.47.2-hdb6dae5_0         conda-forge
      libzlib:         1.3.1-hd23fc13_2          conda-forge
      ncurses:         6.5-hf036a51_1            conda-forge
      openssl:         3.4.0-hd471939_0          conda-forge
      python:          3.12.8-h9ccd52b_1_cpython conda-forge
      python_abi:      3.12-5_cp312              conda-forge
      readline:        8.2-h9e318b2_1            conda-forge
      tk:              8.6.13-h1abcd95_1         conda-forge
      tzdata:          2024b-hc8b5060_0          conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
   flye -h
   grep Assembly
   python -c 'import flye.tests.test_toy as t; t.main()'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/opt/mambaforge/envs/bioconda/conda-bld/flye_1733981834095/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/flye/tests/test_toy.py", line 18, in <module>
      from distutils.spawn import find_executable
  ModuleNotFoundError: No module named 'distutils'
  WARNING: Tests failed for flye-2.9.5-py312he0d4a5b_2.tar.bz2 - moving package to /opt/mambaforge/envs/bioconda/conda-bld/broken
  Traceback (most recent call last):
  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/flye_1733981834095/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3523, in test
  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/flye_1733981834095/test_tmp
  Assembly of long reads with repeat graphs
      utils.check_call_env(
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/flye_1733981834095/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3727, in build_tree
      test(pkg, config=metadata.config.copy(), stats=stats)
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3537, in test
      tests_failed(
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3584, in tests_failed
      raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: flye-2.9.5-py312he0d4a5b_2.tar.bz2
# Last 100 lines of the build log.
