recipe_sha: bef5f0e60eaff31b34ff0963c3e1be8e085900ee919d0d6baeac7b44de727b14  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1656:11: error: 'uint32' does not name a type; did you mean 'uint32_t'?
   1656 |   virtual uint32 LogSize() = 0;
        |           ^~~~~~
        |           uint32_t
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1662:26: error: expected initializer before '*' token
   1662 | extern GLOG_EXPORT Logger* GetLogger(LogSeverity level);
        |                          ^
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1667:8: error: two or more data types in declaration of 'SetLogger'
   1667 | extern GLOG_EXPORT void SetLogger(LogSeverity level, Logger* logger);
        |        ^~~~~~~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1667:35: error: 'LogSeverity' was not declared in this scope; did you mean 'google::LogSeverity'?
   1667 | extern GLOG_EXPORT void SetLogger(LogSeverity level, Logger* logger);
        |                                   ^~~~~~~~~~~
        |                                   google::LogSeverity
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/log_severity.h:62:6: note: 'google::LogSeverity' declared here
     62 | enum LogSeverity {
        |      ^~~~~~~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1667:54: error: 'Logger' was not declared in this scope; did you mean 'base::Logger'?
   1667 | extern GLOG_EXPORT void SetLogger(LogSeverity level, Logger* logger);
        |                                                      ^~~~~~
        |                                                      base::Logger
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1628:19: note: 'base::Logger' declared here
   1628 | class GLOG_EXPORT Logger {
        |                   ^~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1667:62: error: 'logger' was not declared in this scope
   1667 | extern GLOG_EXPORT void SetLogger(LogSeverity level, Logger* logger);
        |                                                              ^~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1669:1: error: expected declaration before '}' token
   1669 | }  // namespace base
        | ^
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1672:30: error: expected initializer before ':' token
   1672 | class GLOG_EXPORT NullStream : public LogMessage::LogStream {
        |                              ^
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1697:8: error: 'NullStream' does not name a type
   1697 | inline NullStream& operator<<(NullStream& str, const T&) {
        |        ^~~~~~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1703:35: error: expected initializer before ':' token
   1703 | class GLOG_EXPORT NullStreamFatal : public NullStream {
        |                                   ^
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1727:1: error: two or more data types in declaration of 'InstallFailureSignalHandler'
   1727 | GLOG_EXPORT void InstallFailureSignalHandler();
        | ^~~~~~~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1730:1: error: two or more data types in declaration of 'IsFailureSignalHandlerInstalled'
   1730 | GLOG_EXPORT bool IsFailureSignalHandlerInstalled();
        | ^~~~~~~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1736:1: error: two or more data types in declaration of 'InstallFailureWriter'
   1736 | GLOG_EXPORT void InstallFailureWriter(void (*writer)(const char* data,
        | ^~~~~~~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1740:25: error: expected initializer before 'GetStackTrace'
   1740 | GLOG_EXPORT std::string GetStackTrace();
        |                         ^~~~~~~~~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:1742:1: error: expected declaration before '}' token
   1742 | }  // namespace google
        | ^
  /opt/conda/conda-bld/cassiopee_1734063569925/work/src/cassiopee.cxx: In constructor 'CassieIndexer::CassieIndexer(const char*)':
  /opt/conda/conda-bld/cassiopee_1734063569925/work/src/cassiopee.cxx:511:9: error: 'LogMessageFatal' is not a member of 'google'; did you mean 'LogMessageTime'?
    511 |         LOG(FATAL) << "Error: " << path << " could not be opened for reading!" ;
        |         ^~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h: In instantiation of 'std::unique_ptr<std::__cxx11::basic_string<char> > google::logging::MakeCheckOpString(const T1&, const T2&, const char*) [with T1 = int; T2 = int]':
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:737:1:   required from 'std::unique_ptr<std::__cxx11::basic_string<char> > google::logging::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = int; T2 = int]'
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:737:1:   required from here
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:710:25: error: 'MakeCheckOpValueString' was not declared in this scope; did you mean 'google::logging::internal::MakeCheckOpValueString'?
    710 |   MakeCheckOpValueString(comb.ForVar1(), v1);
        |   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
        |   google::logging::internal::MakeCheckOpValueString
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:653:13: note: 'google::logging::internal::MakeCheckOpValueString' declared here
    653 | inline void MakeCheckOpValueString(std::ostream* os, const T& v) {
        |             ^~~~~~~~~~~~~~~~~~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:711:25: error: 'MakeCheckOpValueString' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation
    711 |   MakeCheckOpValueString(comb.ForVar2(), v2);
        |   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
  /opt/conda/conda-bld/cassiopee_1734063569925/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/glog/logging.h:710:25: note: 'MakeCheckOpValueString' declared here, later in the translation unit
    710 |   MakeCheckOpValueString(comb.ForVar1(), v1);
        |   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
  make[2]: *** [src/CMakeFiles/cassie.dir/build.make:79: src/CMakeFiles/cassie.dir/cassiopee.cxx.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:163: src/CMakeFiles/cassie.dir/all] Error 2
  make: *** [Makefile:146: all] Error 2
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2558, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/cassiopee_1734063569925/work/conda_build.sh']' returned non-zero exit status 2.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
      raise BuildScriptException(str(exc), caused_by=exc) from exc
  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/cassiopee_1734063569925/work/conda_build.sh']' returned non-zero exit status 2.
# Last 100 lines of the build log.
