recipe_sha: b0e4de2c7b128d2b6d647c2d879bce4d9e1fadf4fa0edb85eeb5b1001fcd60a8  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
      xorg-libxdmcp:             1.1.5-hb9d3cd8_0           conda-forge
      xorg-libxext:              1.3.6-hb9d3cd8_0           conda-forge
      xorg-libxrender:           0.9.11-hb9d3cd8_2          conda-forge
      xorg-libxt:                1.3.1-hb9d3cd8_0           conda-forge
      xz:                        5.6.3-hbcc6ac9_1           conda-forge
      xz-gpl-tools:              5.6.3-hbcc6ac9_1           conda-forge
      xz-tools:                  5.6.3-hb9d3cd8_1           conda-forge
      zstd:                      1.5.6-ha6fb4c9_0           conda-forge

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2439, in build
      create_build_envs(top_level_pkg, notest)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2213, in create_build_envs
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1050, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1338, in _execute_actions
      progressive_fetch_extract.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 900, in execute
      raise CondaMultiError(not_cancelled)
  conda.CondaMultiError: Error with archive /opt/conda/pkgs/gxx_impl_linux-64-14.2.0-h2c03514_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Failed to write to /opt/conda/pkgs/r-lava-1.8.0-r44hc72bb7e_0.conda.partial
    errno: 28
  Error with archive /opt/conda/pkgs/libstdcxx-devel_linux-64-14.2.0-h41c2201_101.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Failed to write to /opt/conda/pkgs/r-lava-1.8.0-r44hc72bb7e_0.conda.partial
    errno: 28
  Failed to write to /opt/conda/pkgs/r-nlme-3.1_165-r44hbcb9c34_1.conda.partial
    errno: 28
  Error with archive /opt/conda/pkgs/binutils_impl_linux-64-2.43-h4bf12b8_2.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/r-survival-3.7_0-r44hdb488b9_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Failed to write to /opt/conda/pkgs/r-sass-0.4.9-r44ha18555a_1.conda.partial
    errno: 28
  Failed to write to /opt/conda/pkgs/r-emmeans-1.10.5-r44hc72bb7e_0.conda.partial
    errno: 28
  Error with archive /opt/conda/pkgs/numpy-2.2.0-py313hb30382a_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/pandoc-3.6-ha770c72_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/r-ggplot2-3.5.1-r44hc72bb7e_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/r-bslib-0.8.0-r44hc72bb7e_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/r-doby-4.6.24-r44hc72bb7e_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/r-lme4-1.1_35.5-r44h0d4f4ea_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/r-matrix-1.6_5-r44he966344_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/r-caret-6.0_94-r44hdb488b9_2.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/libglib-2.82.2-h2ff4ddf_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/libsanitizer-14.2.0-h2a3dede_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/r-colorspace-2.1_1-r44hdb488b9_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device: '/opt/conda/pkgs/r-colorspace-2.1_1-r44hdb488b9_0/lib/R/library/colorspace/cvdemulator'
  Error with archive /opt/conda/pkgs/r-mgcv-1.9_1-r44h0d28552_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Failed to write to /opt/conda/pkgs/gcc_impl_linux-64-14.2.0-h6b349bd_1.conda.partial
    errno: 28
  Error with archive /opt/conda/pkgs/gsl-2.7-he838d99_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/python-3.13.1-ha99a958_102_cp313.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/libgcc-devel_linux-64-14.2.0-h41c2201_101.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/sysroot_linux-64-2.17-h4a8ded7_18.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
# Last 100 lines of the build log.
