recipe_sha: dacf07a8db64d234ae62dffa6e485f753f487342831d5fcc9bc46f9bebc90d8f  # The commit at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
    406 |   enum class byte : unsigned char;
        |                              ^~~~
  myutils.h:42:23: note:                 'typedef unsigned char byte'
     42 | typedef unsigned char byte;
        |                       ^~~~
  seqdb.cpp: In member function 'unsigned int SeqDB::AddSeq(const char*, const int*, unsigned int)':
  seqdb.cpp:231:17: error: reference to 'byte' is ambiguous
    231 |                 byte **NewSeqs = MYALLOC(byte *, NewSize, SeqDB);
        |                 ^~~~
  /opt/conda/conda-bld/mothur_1685382522060/_build_env/x86_64-conda-linux-gnu/include/c/12.2.0/bits/cpp_type_traits.h:406:30: note: candidates are: 'enum class std::byte'
    406 |   enum class byte : unsigned char;
        |                              ^~~~
  myutils.h:42:23: note:                 'typedef unsigned char byte'
     42 | typedef unsigned char byte;
        |                       ^~~~
  seqdb.cpp:231:24: error: 'NewSeqs' was not declared in this scope
    231 |                 byte **NewSeqs = MYALLOC(byte *, NewSize, SeqDB);
        |                        ^~~~~~~
  seqdb.cpp:231:42: error: reference to 'byte' is ambiguous
    231 |                 byte **NewSeqs = MYALLOC(byte *, NewSize, SeqDB);
        |                                          ^~~~
  myutils.h:154:26: note: in definition of macro 'myalloc'
    154 | #define myalloc(t, n)   (t *) mymalloc((n)*sizeof(t))
        |                          ^
  seqdb.cpp:231:34: note: in expansion of macro 'MYALLOC'
    231 |                 byte **NewSeqs = MYALLOC(byte *, NewSize, SeqDB);
        |                                  ^~~~~~~
  /opt/conda/conda-bld/mothur_1685382522060/_build_env/x86_64-conda-linux-gnu/include/c/12.2.0/bits/cpp_type_traits.h:406:30: note: candidates are: 'enum class std::byte'
    406 |   enum class byte : unsigned char;
        |                              ^~~~
  myutils.h:42:23: note:                 'typedef unsigned char byte'
     42 | typedef unsigned char byte;
        |                       ^~~~
  myutils.h:154:29: error: expected primary-expression before ')' token
    154 | #define myalloc(t, n)   (t *) mymalloc((n)*sizeof(t))
        |                             ^
  timing.h:225:41: note: in expansion of macro 'myalloc'
    225 | #define MYALLOC(Type, N, Name)          myalloc(Type, N)
        |                                         ^~~~~~~
  seqdb.cpp:231:34: note: in expansion of macro 'MYALLOC'
    231 |                 byte **NewSeqs = MYALLOC(byte *, NewSize, SeqDB);
        |                                  ^~~~~~~
  seqdb.cpp:237:38: error: 'm_Seqs' was not declared in this scope
    237 |                         NewSeqs[i] = m_Seqs[i];
        |                                      ^~~~~~
  seqdb.cpp:242:24: error: 'm_Seqs' was not declared in this scope
    242 |                 MYFREE(m_Seqs, m_SeqCount, SeqDB);
        |                        ^~~~~~
  timing.h:226:48: note: in definition of macro 'MYFREE'
    226 | #define MYFREE(Array, N, Name)          myfree(Array)
        |                                                ^~~~~
  seqdb.cpp:252:9: error: 'm_Seqs' was not declared in this scope
    252 |         m_Seqs[Index] = MYALLOC(byte, L, SeqDB);
        |         ^~~~~~
  seqdb.cpp:252:33: error: reference to 'byte' is ambiguous
    252 |         m_Seqs[Index] = MYALLOC(byte, L, SeqDB);
        |                                 ^~~~
  myutils.h:154:26: note: in definition of macro 'myalloc'
    154 | #define myalloc(t, n)   (t *) mymalloc((n)*sizeof(t))
        |                          ^
  seqdb.cpp:252:25: note: in expansion of macro 'MYALLOC'
    252 |         m_Seqs[Index] = MYALLOC(byte, L, SeqDB);
        |                         ^~~~~~~
  /opt/conda/conda-bld/mothur_1685382522060/_build_env/x86_64-conda-linux-gnu/include/c/12.2.0/bits/cpp_type_traits.h:406:30: note: candidates are: 'enum class std::byte'
    406 |   enum class byte : unsigned char;
        |                              ^~~~
  myutils.h:42:23: note:                 'typedef unsigned char byte'
     42 | typedef unsigned char byte;
        |                       ^~~~
  myutils.h:154:29: error: expected primary-expression before ')' token
    154 | #define myalloc(t, n)   (t *) mymalloc((n)*sizeof(t))
        |                             ^
  timing.h:225:41: note: in expansion of macro 'myalloc'
    225 | #define MYALLOC(Type, N, Name)          myalloc(Type, N)
        |                                         ^~~~~~~
  seqdb.cpp:252:25: note: in expansion of macro 'MYALLOC'
    252 |         m_Seqs[Index] = MYALLOC(byte, L, SeqDB);
        |                         ^~~~~~~
  make[1]: *** [makefile:21: seqdb.o] Error 1
  make[1]: Leaving directory '$SRC_DIR/source/uchime_src'
  make: *** [Makefile:128: uchime] Error 2
  make: *** Waiting for unfinished jobs....
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
      call_conda_build(action, config)
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
      result = api.build(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
      return build_tree(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
      packages_from_this = build(metadata, stats,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2198, in build
      utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 451, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/mothur_1685382522060/work/conda_build.sh']' returned non-zero exit status 2.
# Last 100 lines of the build log.
