recipe_sha: c40ea3b38417b11c9978f772847dbac6d94e8132f0e6e7626f889a4375865687  # The commit at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  INFO:conda_build.variants:Adding in variants from internal_defaults
  INFO:conda_build.variants:Adding in variants from /opt/mambaforge/envs/bioconda/conda_build_config.yaml
  INFO:conda_build.variants:Adding in variants from /opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
  Attempting to finalize metadata for gat
  INFO:conda_build.metadata:Attempting to finalize metadata for gat
  conda-forge/osx-64                                          Using cache
  conda-forge/noarch                                          Using cache
  bioconda/osx-64                                             Using cache
  bioconda/noarch                                             Using cache
  Reloading output folder: /opt/mambaforge/envs/bioconda/conda-bld
  Reloading output folder: /opt/mambaforge/envs/bioconda/conda-bld
  Mamba failed to solve:
   - zlib 1.2.*
   - numpy >=1.7,<1.20
   - cython >=0.19
   - python 3.10.* *_cpython
   - matplotlib >=1.3.0
   - setuptools >=1.1
   - scipy >=0.11

  with channels:
   - conda-forge
   - bioconda
   - defaults

  The reported errors are:
  - Encountered problems while solving:
  -   - package python-3.10.4-h8b4d769_0_cpython requires libzlib >=1.2.11,<1.3.0a0, but none of the providers can be installed
  -

  Leaving build/test directories:
    Work:
   /opt/mambaforge/envs/bioconda/conda-bld/work
    Test:
   /opt/mambaforge/envs/bioconda/conda-bld/test_tmp
  Leaving build/test environments:
    Test:
  source activate  /opt/mambaforge/envs/bioconda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
    Build:
  source activate  /opt/mambaforge/envs/bioconda/conda-bld/_build_env


  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
      solution = solver.solve_for_action(_specs, prefix)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/core/solver.py", line 230, in solve_for_action
      t = self.solve(specs)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/core/solver.py", line 220, in solve
      raise RuntimeError("Solver could not find solution."  error_string)
  RuntimeError: Solver could not find solution.Mamba failed to solve:
   - zlib 1.2.*
   - numpy >=1.7,<1.20
   - cython >=0.19
   - python 3.10.* *_cpython
   - matplotlib >=1.3.0
   - setuptools >=1.1
   - scipy >=0.11

  with channels:
   - conda-forge
   - bioconda
   - defaults

  The reported errors are:
  - Encountered problems while solving:
  -   - package python-3.10.4-h8b4d769_0_cpython requires libzlib >=1.2.11,<1.3.0a0, but none of the providers can be installed
  -

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/bin/conda-mambabuild", line 10, in <module>
      sys.exit(main())
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
      call_conda_build(action, config)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
      result = api.build(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
      return build_tree(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
      packages_from_this = build(metadata, stats,
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 2038, in build
      output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 787, in expand_outputs
      for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/metadata.py", line 2524, in get_output_metadata_set
      conda_packages = finalize_outputs_pass(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/metadata.py", line 884, in finalize_outputs_pass
      fm = finalize_metadata(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 547, in finalize_metadata
      build_unsat, host_unsat = add_upstream_pins(m,
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 409, in add_upstream_pins
      host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 374, in _read_upstream_pin_files
      deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 131, in get_env_dependencies
      actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 150, in mamba_get_install_actions
      raise err
  conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {MatchSpec("python==3.10.4=h8b4d769_0_cpython"), MatchSpec("libzlib[version='>=1.2.11,<1.3.0a0']")}
# Last 100 lines of the build log.
